version: '3.8'

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus # Use named volume for Prometheus data
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      monitoring:
        ipv4_address: 172.20.0.2

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /opt/nginx/html:/usr/share/nginx/html
      - /opt/nginx/conf.d:/etc/nginx/conf.d
    networks:
      monitoring:
        ipv4_address: 172.20.0.3

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    restart: unless-stopped
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status'
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      monitoring:
        ipv4_address: 172.20.0.4

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      monitoring:
        ipv4_address: 172.20.0.5
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - /opt/grafana/datasources/prometheus-source.yml:/etc/grafana/provisioning/datasources/prometheus-source.yml:ro
      - /opt/grafana/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:r
      - /opt/grafana/dashboards/default:/etc/grafana/provisioning/dashboards/default:ro
    environment:
      - GF_PROVISIONING_DASHBOARDS_DEFAULT_ENABLED=true # enable dashboard provisioning

volumes:
  prometheus_data:
  grafana_data:
