version: '3.8'

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: "65534:65534"  # Run as nobody:nogroup for proper permissions
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=0.0.0.0:9090'  # Ensure it listens on all interfaces
    ports:
      - "9090:9090"
    networks:
      monitoring:
        ipv4_address: 172.20.0.2

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /opt/nginx/html:/usr/share/nginx/html
      - /opt/nginx/conf.d:/etc/nginx/conf.d  # Mount the configuration directory
    networks:
      monitoring:
        ipv4_address: 172.20.0.3

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    restart: unless-stopped
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status'
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      monitoring:
        ipv4_address: 172.20.0.4